name: "custom action workflow"

on : [push]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v

            - name: Run Coderco-Custom action
              uses: salim1704/Coderco-Custom@main
              with:
                who-to-greet: 'GitHub Actions'
        