name: Build and Push Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r task_2/requirements.txt

      - name: Analyzing the code with pylint
        run: |
          cd task_2
          pylint app.py

      - name: Run tests with pytest
        run: |
          cd task_2
          pytest test_app.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./task_2
          file: ./task_2/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/task-2:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/task-2:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_HOST_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            APP_DIR="/home/ec2-user/ci-cd-app/task_2"
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/salim1704/CI-CD.git "$APP_DIR"
            else
              cd "$APP_DIR"
              git pull
            fi
            docker compose pull
            docker compose up -d
            docker image prune -f
